import { ServicePlan } from './supabase';

export const SERVICE_PLANS_DATA: ServicePlan[] = [
  {
    id: 'free',
    name_uz: "Asosiy",
    name_ru: "Базовый",
    name_en: "Basic",
    tagline_uz: "Boshlang'ich dehqonlar va kichik tomorqa xo'jaliklari uchun bepul monitoring",
    tagline_ru: "Бесплатный мониторинг для начинающих дехкан и небольших участков",
    tagline_en: "Free essential satellite monitoring for smallholders & hobby farmers",
    price_monthly_uzs: 0,
    popular: false,
    features_uz: [
      "1 ta ekin maydonini ro'yxatdan o'tkazish",
      "Haftalik sun'iy yo'ldosh NDVI yashillik tahlili",
      "Umumiy 3 kunlik ob-havo ma'lumotlari",
      "Agro-qo'llanma va o'sish bosqichlari tavsiyalari",
      "Hosil bozoriga bepul e'lonlar joylash",
    ],
    features_ru: [
      "Регистрация 1 поля",
      "Еженедельный анализ индекса вегетации NDVI",
      "Базовый прогноз погоды на 3 дня",
      "Агро-справочник и рекомендации по фазам",
      "Публикация урожая на агрорынке",
    ],
    features_en: [
      "1 field boundary registration",
      "Weekly Sentinel satellite NDVI vegetation updates",
      "3-day basic agro-weather forecast",
      "Crop guides and seasonal phase notes",
      "Free marketplace harvest listings",
    ],
    limitations_uz: [
      "Faqat 1 ta maydon bilan cheklangan",
      "AI mavsumiy xulosalar mavjud emas",
      "Agronom bilan hamkorlik yo'q",
    ],
    limitations_ru: [
      "Ограничение 1 полем",
      "Без сезонных отчётов ИИ",
      "Без доступа к агроному",
    ],
    limitations_en: [
      "Limited to 1 single field",
      "No AI seasonal narrative summaries",
      "No direct agronomist collaboration",
    ],
  },
  {
    id: 'standart',
    name_uz: "Standart",
    name_ru: "Стандарт",
    name_en: "Standard",
    tagline_uz: "Faol fermerlar va o'rta xo'jaliklar uchun to'liq agrometeorologik va sug'orish nazorati",
    tagline_ru: "Полный агрометеорологический и поливной контроль для активных фермеров",
    tagline_en: "Complete precision irrigation and weather telemetry for commercial farms",
    price_monthly_uzs: 45000,
    price_per_ha_uzs: 15000,
    popular: true,
    features_uz: [
      "Cheksiz miqdordagi maydonlarni qo'shish",
      "Har 3-5 kunda sun'iy yo'ldosh yangilanishi",
      "7 kunlik aniq agrometeorologik sug'orish kalkulyatori",
      "Tarixiy NDVI va tuproq namligi grafiklari dinamikasi",
      "Tuproq namligi va qurg'oqchilik xavfi ogohlantirishlari",
      "Mavsum bosqichlari (Milestones) to'liq monitoringi",
      "Dala poligonlarini KML / GeoJSON formatda yuklab olish",
    ],
    features_ru: [
      "Неограниченное количество полей",
      "Спутниковое обновление каждые 3-5 дней",
      "7-дневный точный калькулятор норм полива",
      "История динамики NDVI и влажности почвы",
      "Оповещения о риске засухи и водного стресса",
      "Полный трекер сезонных фаз (Milestones)",
      "Экспорт границ полей в KML / GeoJSON",
    ],
    features_en: [
      "Unlimited field boundaries & multi-plot tracking",
      "High-frequency 3-5 day satellite imagery refresh",
      "7-day precision evapotranspiration irrigation calculator",
      "Historical NDVI & moisture trend analytics",
      "Early drought and moisture depletion alerts",
      "Complete season milestone tracker & checklists",
      "Field boundary export (KML / GeoJSON)",
    ],
    limitations_uz: [
      "AI xulosalari haftasiga 3 marta bilan cheklangan",
    ],
    limitations_ru: [
      "ИИ-отчёты ограничены 3 разами в неделю",
    ],
    limitations_en: [
      "AI reports limited to 3 per week",
    ],
  },
  {
    id: 'pro',
    name_uz: "Professional",
    name_ru: "Профессионал",
    name_en: "Professional",
    tagline_uz: "Yirik klasterlar, eksportchilar va agronomlar uchun AI yordamchisi va to'liq konsultatsiya",
    tagline_ru: "ИИ-ассистент, агрономическое сотрудничество и субсидии для крупных хозяйств",
    tagline_en: "Full AI Agronomist assistant, advisor collaboration, and subsidy matching",
    price_monthly_uzs: 120000,
    price_per_ha_uzs: 35000,
    popular: false,
    features_uz: [
      "Standart rejaning barcha imkoniyatlari",
      "✨ AI Ekin Yordamchisi (Gemini): Cheksiz chuqur agronomik tahlillar",
      "🤝 Agronom bilan to'g'ridan-to'g'ri hamkorlik va dala xulosalari (Taranis AgTech)",
      "🏛️ Davlat subsidiyalarini avtomatik moslashtirish va ariza ko'magi",
      "📊 PDF formatdagi rasmiy agro-monitoring hisobotlarini chop etish",
      "⚡ Shoshilinch xavf-xatar bildirishnomalari (SMS / Telegram bot)",
      "📞 24/7 ustuvor agronomik va texnik yordam",
    ],
    features_ru: [
      "Все возможности тарифа «Стандарт»",
      "✨ ИИ-ассистент (Gemini): Безлимитные экспертные агро-отчёты",
      "🤝 Прямое сотрудничество с агрономом и инспекции (Taranis AgTech)",
      "🏛️ Подбор и подготовка документов на гос. субсидии",
      "📊 Экспорт официальных PDF отчётов для банков и кластеров",
      "⚡ Срочные оповещения о рисках (SMS / Telegram)",
      "📞 Приоритетная поддержка агронома 24/7",
    ],
    features_en: [
      "All Standard plan capabilities included",
      "✨ AI Ag Assistant (Gemini): Unlimited deep agronomic diagnostic reports",
      "🤝 Direct Agronomist collaboration & field action orders (Taranis AgTech)",
      "🏛️ Automated Government Subsidy & grant matching with application help",
      "📊 Official printable PDF agro-telemetry reports for banks & clusters",
      "⚡ Urgent crop stress alerts via SMS and Telegram",
      "📞 24/7 priority agronomist and agronomy team support",
    ],
  },
];
